param(
    [switch]$CheckOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$LaunchRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$AppRoot = $LaunchRoot
if (Test-Path (Join-Path $LaunchRoot "app\pyproject.toml")) {
    $AppRoot = Join-Path $LaunchRoot "app"
}
$VenvRoot = Join-Path $LaunchRoot ".venv"
$VenvPython = Join-Path $VenvRoot "Scripts\python.exe"
$DependencyStamp = Join-Path $VenvRoot ".aura_deps_installed"
$DiagnosticReport = Join-Path $LaunchRoot "diagnostic_report.txt"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "== $Message =="
}

function Resolve-Python311 {
    if (Test-Path $VenvPython) {
        return $VenvPython
    }

    $pyLauncher = Get-Command py -ErrorAction SilentlyContinue
    if ($pyLauncher) {
        & py -3.11 -c "import sys; raise SystemExit(0 if sys.version_info[:2] == (3, 11) else 1)" | Out-Null
        if ($LASTEXITCODE -eq 0) {
            return "py -3.11"
        }
    }

    $python = Get-Command python -ErrorAction SilentlyContinue
    if ($python) {
        & python -c "import sys; raise SystemExit(0 if sys.version_info[:2] == (3, 11) else 1)" | Out-Null
        if ($LASTEXITCODE -eq 0) {
            return "python"
        }
    }

    throw "Python 3.11 was not found. Install Python 3.11, then run Start-AURA again."
}

function Invoke-Python {
    param(
        [string]$PythonCommand,
        [string[]]$Arguments
    )

    if ($PythonCommand -eq "py -3.11") {
        & py -3.11 @Arguments
    } else {
        & $PythonCommand @Arguments
    }
    if ($LASTEXITCODE -ne 0) {
        throw "Python command failed with exit code $LASTEXITCODE: $PythonCommand $($Arguments -join ' ')"
    }
}

function Resolve-AuraScript {
    param([string]$RelativePath)

    $rootScript = Join-Path $LaunchRoot $RelativePath
    if (Test-Path $rootScript) {
        return $rootScript
    }
    return Join-Path $AppRoot $RelativePath
}

function Write-DiagnosticReport {
    param(
        [string]$PythonCommand,
        [string]$Status
    )

    $reportScript = Resolve-AuraScript "scripts\runtime_report.py"
    $header = @(
        "Project AURA Diagnostic Report",
        "Generated by Start-AURA.ps1",
        "Status: $Status",
        ""
    ) -join [Environment]::NewLine
    Set-Content -Encoding UTF8 -Path $DiagnosticReport -Value $header

    if ((Test-Path $reportScript) -and $PythonCommand) {
        try {
            Invoke-Python $PythonCommand @($reportScript) 2>&1 | Out-File -Encoding UTF8 -Append $DiagnosticReport
        } catch {
            "runtime_report.py failed: $($_.Exception.Message)" | Out-File -Encoding UTF8 -Append $DiagnosticReport
        }
    } else {
        "runtime_report.py was not available." | Out-File -Encoding UTF8 -Append $DiagnosticReport
    }
}

$ResolvedPython = ""
try {
    Set-Location $AppRoot

    Write-Step "Checking Python 3.11"
    $ResolvedPython = Resolve-Python311
    Write-Host "Python command: $ResolvedPython"

    if (-not (Test-Path $VenvPython)) {
        Write-Step "Creating virtual environment"
        Invoke-Python $ResolvedPython @("-m", "venv", $VenvRoot)
    }

    $ResolvedPython = $VenvPython

    Write-Step "Preparing pip"
    Invoke-Python $ResolvedPython @("-m", "ensurepip", "--upgrade")
    Invoke-Python $ResolvedPython @("-m", "pip", "install", "-U", "pip")

    $pyproject = Join-Path $AppRoot "pyproject.toml"
    $needsInstall = -not (Test-Path $DependencyStamp)
    if ((Test-Path $pyproject) -and (Test-Path $DependencyStamp)) {
        $needsInstall = (Get-Item $pyproject).LastWriteTimeUtc -gt (Get-Item $DependencyStamp).LastWriteTimeUtc
    }
    if (-not $needsInstall) {
        & $ResolvedPython -c "import aura, torch, transformers" 2>$null
        $needsInstall = $LASTEXITCODE -ne 0
    }
    if ($needsInstall) {
        Write-Step "Installing Project AURA dependencies"
        Invoke-Python $ResolvedPython @("-m", "pip", "install", "-e", ".[summary,punctuation]")
        Set-Content -Encoding ASCII -Path $DependencyStamp -Value (Get-Date -Format o)
    } else {
        Write-Step "Dependencies already prepared"
    }

    Write-Step "Checking FFmpeg"
    if (-not (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {
        throw "FFmpeg was not found on PATH. Install FFmpeg or add it to PATH."
    }
    if (-not (Get-Command ffprobe -ErrorAction SilentlyContinue)) {
        throw "ffprobe was not found on PATH. Install FFmpeg or add it to PATH."
    }
    Write-Host "FFmpeg and ffprobe are available."

    Write-Step "Checking NVIDIA driver"
    if (-not (Get-Command nvidia-smi -ErrorAction SilentlyContinue)) {
        throw "nvidia-smi was not found on PATH. Install or update the NVIDIA driver."
    }
    nvidia-smi
    if ($LASTEXITCODE -ne 0) {
        throw "nvidia-smi failed with exit code $LASTEXITCODE."
    }

    Write-Step "Writing diagnostic report"
    Write-DiagnosticReport $ResolvedPython "pre-launch checks"
    Write-Host "Diagnostic report: $DiagnosticReport"

    Write-Step "Checking Windows RTX/CUDA ASR path"
    $gpuSmoke = Resolve-AuraScript "scripts\windows_gpu_smoke.py"
    Invoke-Python $ResolvedPython @($gpuSmoke)

    Write-DiagnosticReport $ResolvedPython "ready"
    if ($CheckOnly) {
        Write-Host ""
        Write-Host "Project AURA runtime checks completed."
        Write-Host "Diagnostic report written to: $DiagnosticReport"
        exit 0
    }

    Write-Step "Starting Project AURA"
    Invoke-Python $ResolvedPython @("-m", "aura")
} catch {
    $message = $_.Exception.Message
    Write-Host ""
    Write-Host "Project AURA could not start: $message" -ForegroundColor Red
    try {
        Write-DiagnosticReport $ResolvedPython "failed: $message"
        Write-Host "Diagnostic report written to: $DiagnosticReport"
    } catch {
        Write-Host "Could not write diagnostic report: $($_.Exception.Message)" -ForegroundColor Yellow
    }
    exit 1
}
